# Generated by Django 3.2.7 on 2021-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('DDD', models.IntegerField(max_length=3)),
                ('Telefone', models.IntegerField(max_length=9)),
                ('Cidade', models.CharField(max_length=30)),
                ('Idade', models.IntegerField(max_length=3)),
                ('Valor', models.FloatField(max_length=10)),
            ],
        ),
    ]
